### ISSUE TITLE
Problemas com o ComparartorPorPreco(), Quandos instanciado um treeset

### ISSUE THREAD

**Issue by Senuy** [cami-la/collections-java-api-2023#103]
No exemplo de ordenacao de Sets, no método exibirPorPreco(), ele não instancia a classe ComparatorPorPreco, gerando esse exceção 

Exception in thread "main" java.lang.Error: Unresolved compilation problem: 
	ComparatorPorPreco cannot be resolved to a type

	at set.ordenacao.cadastroProdutos.CadastroProdutos.exibirPorPreco(CadastroProdutos.java:29)
	at set.ordenacao.cadastroProdutos.CadastroProdutos.main(CadastroProdutos.java:50)

![image](https://github.com/user-attachments/assets/da9cd65e-964d-4151-98c0-082f677d1a6e)

**Comment by Senuy** [comment]
erro no posicionamento da classe comparator dentro do arquivo Produto.java
